# Generated by Django 5.0.3 on 2024-04-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="image",
            field=models.ImageField(null=True, upload_to="hotel_images/"),
        ),
    ]
